### ISSUE TITLE
Support for multi-module project structure

### ISSUE THREAD

**Issue by mthmulders** [khmarbaise/maven-it-extension#167]
**Is your feature request related to a problem? Please describe.**
I'm writing a Maven plugin. The implementation is divided over multiple Maven modules in a multi-module setup. One of the modules contains the integration tests with this Integration Testing Framework.

In the **tests** module I have bound the **install** goal of the **itf-maven-plugin** to the **pre-integration-test** phase.

When I run `mvn verify` the output contains this:

```
[INFO] Installing <path-to-project>/pom.xml to <path-to-project>/tests/target/itf-repo/it/mulders/puml/puml-parent/0.1-SNAPSHOT/puml-parent-0.1-SNAPSHOT.pom
[INFO] Installing <path-to-project>/tests/pom.xml to <path-to-project>/tests/target/itf-repo/it/mulders/puml/plugin-tests/0.1-SNAPSHOT/plugin-tests-0.1-SNAPSHOT.pom
[INFO] Installing <path-to-project>/tests/target/plugin-tests-0.1-SNAPSHOT.jar to <path-to-project>/tests/target/itf-repo/it/mulders/puml/plugin-tests/0.1-SNAPSHOT/plugin-tests-0.1-SNAPSHOT.jar
```

As you can see, it installs the project **parent** and the **tests** - but it does not install the plugin itself. As one would expect, **mvn-stdout.log** contains:

```
[ERROR] Plugin it.mulders.puml:plantuml-maven-plugin:0.1-SNAPSHOT or one of its dependencies could not be resolved: Could not find artifact it.mulders.puml:plantuml-maven-plugin:jar:0.1-SNAPSHOT -> [Help 1]
```

I think this means that I cannot use this Integration Testing Framework with a multi-module project setup?

**Describe the solution you'd like**
It would be great if it would be possible to separate the integration tests from the implementation module.

**Describe alternatives you've considered**
I think putting the integration tests in the same Maven module as the implementation is currently the only viable approach.

**Additional context**
My (simplified) project structure looks like this:
```
.
├── maven-plugin
│   └── src
│       ├── main
│       │   ├── java
│       │   └── resources
│       └── test
│           ├── java
│           └── resources
├── ......
│   └── src
│       ├── main
│       │   ├── java
│       │   └── resources
│       └── test
│           ├── java
│           └── resources
└── tests
    └── src
        └── test
            ├── java
            ├── resources
            └── resources-its
```

**Comment by khmarbaise** [comment]
Can you create an example project on Github or alike to I can take a look...

**Comment by mthmulders** [comment]
Of course. You can inspect the [this project](https://github.com/mthmulders/puml-maven-plugin/tree/basic-usage-integration-test). I'm not yet sure if the projects under **tests/src/test/resources-its** should have the project parent as their parent.

**Comment by khmarbaise** [comment]
The is a problem related to your build setup. The `tests` module does not define any dependency to the plugin. This means it is not 100% sure that the build order will be kept or in other words will run in the order you like ( or it should):

This means you have to define a dependency to your plugin in your `tests` module like this:
```xml
        <dependency>
            <groupId>it.mulders.puml</groupId>
            <artifactId>plantuml-maven-plugin</artifactId>
            <version>${project.version}</version>
        </dependency>
```
This has two consequences. First it will automatically define the correct build order and also solves the problem of not having found the plugin code within the integration tests (`plantuml-maven-plugin..jar` could not be found.)

Apart from that related to your question with the project parent. 

I strongly recommend not to make the parent of your IT's the parent of your project cause every time you change your parent this could break your tests. Furthermore the user of your plugin does not use your parent ... so from my point of view that would not be a realistic integration tests scenario.

**Comment by mthmulders** [comment]
Awesome! That indeed covers my use case. I didn't understand from the examples that I needed to have a _dependency_ to a _plugin_ (which is not something I've often seen before...). Thanks, @khmarbaise for your support!

**Comment by khmarbaise** [comment]
Good point. This might be a good improvement for the documentation.

**Comment by khmarbaise** [comment]
See #168
