### ISSUE TITLE
Typo in method name should be isSuccessful

### ISSUE THREAD

**Issue by baerrach** [khmarbaise/maven-it-extension#186]
https://github.com/khmarbaise/maven-it-extension/blob/21f966438e28e9c49f4406a3b9f318127b6ed359/itf-extension-maven/src/main/java/com/soebes/itf/jupiter/maven/MavenExecutionResult.java#L58

The method name has a single "S".

It should be `isSuccesful()`

All the documentation uses the correct spelling, its only MavenExecutionResult that is wrong.

**Comment by khmarbaise** [comment]
Many thanks for reporting that. Of course this is wrong.
