### ISSUE TITLE
Ability to reference the test directory in the pom.xml under test?

### ISSUE THREAD

**Issue by aegershman** [khmarbaise/maven-it-extension#192]
This is a question and looking for advice more than a "bug", really. Apologies if this isn't the right spot.

Given a `pom.xml` under test (e.g., under a directory like `src/test/resources-its/.../SomeIT/some_test/**`), how should configuration paths within the `pom.xml` reference the same directory under test?

**background info**

What I'm trying to do is have the `pom.xml` under test reference another file within the test folder. I'd like to be able to use maven dynamic property resolution (such as `${project.basedir}/rewrite.yml`) within the `pom.xml` to reference the file rather than provide full details on the path.

Here's a specific example of what I mean: https://github.com/openrewrite/rewrite-maven-plugin/blob/0b51dc8b0da87b4652f2b605c4e09e14e69afe51/src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/pom.xml#L27-L29 

I'd like the `pom.xml` to be able to reference the file `rewrite.yml` which is at the same root level as the `pom.xml` in the test folder (specifically: https://github.com/openrewrite/rewrite-maven-plugin/blob/0b51dc8b0da87b4652f2b605c4e09e14e69afe51/src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/rewrite.yml)

If I have the `pom.xml` reference `${project}`, it tries to use the full path to the `pom.xml`, which is close. But I need the base directory. If I use `${project.basedir}`, I get the base directory to the overall plugin, which isn't quite right either.

Currently I'm partially referencing the full path using `                            ${maven.multiModuleProjectDirectory}/src/test/resources-its/org/openrewrite/maven/RewriteDryRunIT/multi_module_project/rewrite.yml`, but I'd like to be able to do something like `${maven.multiModuleProjectDirectory.basedir}/rewrite.yml` (or something to that effect) so I don't need to qualify each test with the path.

Is there any way to do this? Thanks in advance for any guidance, I appreciate your time.

**Comment by khmarbaise** [comment]
Then please use the discussion area https://github.com/khmarbaise/maven-it-extension/discussions

**Comment by aegershman** [comment]
Will do, posted here: https://github.com/khmarbaise/maven-it-extension/discussions/193
