### ISSUE TITLE
README example does not compile

### ISSUE THREAD

**Issue by don-vip** [khmarbaise/maven-it-extension#197]
**Describe the bug**
I'm following the [README](https://github.com/khmarbaise/maven-it-extension#the-testing-code) at the step:
```java
import static org.assertj.core.api.Assertions.assertThat;

import com.soebes.itf.jupiter.extension.MavenJupiterExtension;
import com.soebes.itf.jupiter.extension.MavenTest;
import com.soebes.itf.jupiter.maven.MavenExecutionResult;

@MavenJupiterExtension // <1>
class FirstMavenIT {

  @MavenTest // <2>
  void the_first_test_case(MavenExecutionResult result) { //<3>
    assertThat(result).build().isSuccessful(); // <4>
  }
}
```

**Current behavior**
The code does not compile:
`The method build() is undefined for the type ObjectAssert<MavenExecutionResult>`

**Expected behavior**
Code compiles.
 
**The used versions**
 - Maven 3.8.1
 - OpenJDK 11.0.6
 - Eclipse 2020-03
 - ITF: 0.9.0
 - AssertJ: tried 3.16.1 and 3.19.0

**Comment by khmarbaise** [comment]
@don-vip Hi first many thanks for reporting the issue. Can you please recheck the updated example in the `README.md` ...

**Comment by don-vip** [comment]
Ah, much better, thank you!
