### ISSUE TITLE
Goal itf-maven-plugin:resources-its does not replace placeholder

### ISSUE THREAD

**Issue by rweisleder** [khmarbaise/maven-it-extension#204]
**Describe the bug**
The newly introduced goal `resources-its` to copy resources (#163) does not replace placeholders like `@project.version@`.

**To Reproduce**

1. Create a file `src/test/resources-its/org/example/test.txt` with content
```
Hello World @project.version@
```
2. Run `mvn com.soebes.itf.jupiter.extension:itf-maven-plugin:0.10.0:resources-its`
3. Check the content of `target/test-classes/org/example/test.txt`

**Current behavior**
The content is
```
Hello World @project.version@
```

**Expected behavior**
The content should be something like
```
Hello World 1.0-SNAPSHOT
```

**Comment by rweisleder** [comment]
_in progress_

**Comment by rweisleder** [comment]
PR: #205

**Comment by khmarbaise** [comment]
Many thanks for finding that really annoying bug. Sorry for that.
