### ISSUE TITLE
Support for custom location and reuse of a Maven project from my resources

### ISSUE THREAD

**Issue by filiphr** [khmarbaise/maven-it-extension#232]
We are currently using this extension for something entirely unrelated to the main goal of this project. We are using it to test executions of our example Maven Projects, with different build properties and user access flavours. 

Currently it is not possible to reuse the same example project for multiple standalone test runs.

I know about `@MavenProject`. However, that is not enough for us, since that is mostly used both for the target and source project. What we need is something like `@MavenSourceProject` that would point to a folder in my test resource and copy that folder to the `@MavenProject` or the default location of the target project.

I have already made this work for us by adding a new `@MavenSourceProject` annotation and we are ready to contribute this to the project in case you are interested in this functionality.

**Comment by khmarbaise** [comment]
Please make a full working example and describe more in detail what exactly the purpose the workflow of such setup is...

**Comment by filiphr** [comment]
Let's take an example from the samples of this repository. More specifically [ProfileOnClassIT](https://github.com/khmarbaise/maven-it-extension/tree/master/itf-examples/src/test/resources-its/com/soebes/itf/examples/profiles/ProfileOnClassIT). Here, the projects [profile_1](https://github.com/khmarbaise/maven-it-extension/tree/master/itf-examples/src/test/resources-its/com/soebes/itf/examples/profiles/ProfileOnClassIT/profile_1) and [profile_1_2_3](https://github.com/khmarbaise/maven-it-extension/tree/master/itf-examples/src/test/resources-its/com/soebes/itf/examples/profiles/ProfileOnClassIT/profile_1_2_3) are identical. This means that in theory the defined tests in [ProfileOnClassIT](https://github.com/khmarbaise/maven-it-extension/blob/master/itf-examples/src/test/java/com/soebes/itf/examples/profiles/ProfileOnClassIT.java) might be wrong, only because something is different in the source project.

If we instead have a single project then we can be sure that both test methods are going to run as standalone identical projects. 

The main goal is reducing duplication in the test code. There are more examples from the samples in this code base that could be simplified to use a single source project, e.g. `GoalsIT` and `GoalsOnClassIT`

**Comment by khmarbaise** [comment]
As I mentioned a full working example would be helpful to understand your idea better.

The examples in the examples projects are really examples for this project. Furthermore to reduce duplication is not the main goal here.

But it sounds like this could be a job for `@ParameterizedTest` (something like `@MavenParameterizedTest`) which would fit better from my impression.

**Comment by filiphr** [comment]
OK I will try to prepare some kind of an example that we are using in the moment.

Something like `@Parametrized` test is something that would benefit us a lot as well. I would even argue that even exposing the possibility for configuring the test and running it from our test case would be everything that we need.

I'll prepare an example through a PR, you can then decide and reject it if it isn't good

**Comment by filiphr** [comment]
I've created PR #236 about this example.

**Comment by khmarbaise** [comment]
Hi @filiphr I have not taken your implementation via the given pr but have taken the liberty to take your idea and implemented a bit advanted solution which also solves another problem I had. Thank you very much for your reporting and inspiration.

**Comment by filiphr** [comment]
Thanks a lot @khmarbaise the implementation you did has more functionality than I needed. I'll try it out in our project once there is a release
