### ISSUE TITLE
Test project's file attributes & links get lost when copied to test target/maven-it

### ISSUE THREAD

**Issue by mguillem** [khmarbaise/maven-it-extension#260]
**Describe the bug**
Under Linux, when copying test projects to `target/maven-it` subfolders, executable files loose their executable bit and symbolic links are replaced with the content of the target file.
 
**The used versions**
The version of tools you have used.

 - Maven: 3.6.3
 - JDK: [e.g. OpenJDK 1.8.0_132]
 - ITF: 0.11.0

**Comment by khmarbaise** [comment]
Please show a full project setup best would be having an example project. 

Apart from that why do you have executable files and symbolic links?

**Comment by mguillem** [comment]
Investigating it a bit more, it seems to be a problem of Maven resource plugin as well. The executable bit part of this issue has been fixed there with https://github.com/apache/maven-shared-utils/pull/29.

I can provide a testcase for the itf-maven-plugin project which will naturally fail.

Concretely the plugin for which I want to use maven-it-extension compares the content of an artifact built with Maven assembly plugin with a reference file containing the expected structure (a bit like the output of `tree`). In the case of linux artifacts, the executable bit and symbolic links are verified too.

**Comment by khmarbaise** [comment]
It would be great if you could provide an test case and yes of course it will fail (It must fail first)...
