### ISSUE TITLE
Assign @SystemProperty to class / nested class and inherit on all test methods

### ISSUE THREAD

**Issue by JWT007** [khmarbaise/maven-it-extension#297]
**Is your feature request related to a problem? Please describe.**

The example below is maybe an edge case, but I still think there is potential in the requested feature. :)

We are using the maven-git-versioning-extension in our Git project at the root to set the POM version based on branch name.
(adding extension in ".mvn/extensions.xml" and associated ".mvn/maven-git-versioning-extension.xml".)  

Unfortunately, this is also picked up within the integration tests by default.

So for example, if we want to test that the version of a modified POM is "1.2.3-SNAPSHOT" it is changed to "1.2.3-hotfix-SNAPSHOT".

I have workarounds now by defining the following on every single test-method.
```
  @MavenGoal("install")
  @MavenTest
  @SystemProperty(value = "versioning.disable", content="true") // disable maven-git-versioning-extension for IT tests
  public void test_001(final MavenExecutionResult result) { ... }
```
I tried defining this `@SystemProperty` annotation on the test class (and the `@Nested` classes); however, it does not propagate to the test methods.

**Describe the solution you'd like**

What would be great is to just be able to define the `@SystemProperty` at class-level and have it propagate to all methods (and methods in `@Nested` subclasses).

I am assuming that the same argument might be made for the `@MavenOption` annotation but that is not where I am having the problem. :) 

**Additional context**
Sample error:
```
java.lang.AssertionError: [GAVP] 
Expecting:
  <["me.jwt007.maven.plugins.foobar.its",
    "foobar-bom-001",
    "1.0.1-hotfix-SNAPSHOT",
    "pom"]>
to contain exactly (and in same order):
  <["me.jwt007.maven.plugins.foobar.its", "foobar-bom-001", "1.2.3", "pom"]>
but some elements were not found:
  <["1.2.3"]>
and others were not expected:
  <["1.0.1-hotfix-SNAPSHOT"]>
```

**Comment by khmarbaise** [comment]
Can you create an example project which shows the wrong behaviour? Apart from that it sounds like a bug...

**Comment by JWT007** [comment]
I can try :)

**Comment by JWT007** [comment]
Hallo KH,

here is an example project:

https://github.com/JWT007/maven-it-extension-297

See the README for details:

The concrete problem is defining `@SystemProperty` on the outer class does not propagate to nested classes:

````java
@DisplayName("HelloMojo:")
@MavenJupiterExtension
@MavenRepository
@SystemProperty(value = "versioning.disable", content="true") // disable maven-git-versioning-extension for IT tests
public class HelloMojo1IT {

  @Nested
  @DisplayName("Nested:")
  class NestedClass {

    @DisplayName("... test version")
    @MavenGoal("compile")
    @MavenTest
    public void test_001(MavenExecutionResult result) {...}
````

**mvn-arguments.log**
````text
C:\JWT\SOFTWARE\apache-maven-3.8.6\bin\mvn.cmd
-Dmaven.repo.local=C:\JWT\PRJ\PWC\REPO\maven-it-extension-297\target\maven-it\me\jwt007\maven\plugins\ite\issue297\its\HelloMojo1IT\.m2\repository
--batch-mode
-V
--errors
````

**Comment by JWT007** [comment]
Thx KH, I will give it a try :) Cheers, - Jeff
