### ISSUE TITLE
Version not locked for default bindings plugins

### ISSUE THREAD

**Issue by delanym** [khmarbaise/maven-it-extension#350]
Could you please comment on this issue?

https://github.com/openrewrite/rewrite-maven-plugin/issues/540#issuecomment-1505724595

**Comment by khmarbaise** [comment]
The shown behaviour is based on the different behaviour in Maven 3.9.X vs. 3.8.X which means the test has to handle that in a different way or the integration test project should pin the plugin version to prevent such warning during the build. That is not what the itf framework can solve...
