### ISSUE TITLE
Split assertion library into separate artifact

### ISSUE THREAD

**Issue by sewe** [khmarbaise/maven-it-extension#6]
First of all, this is a really nice project (and also a very good write-up of the limitations of the existing integration-test approachs for Maven plug-ins).

But would it be possible to split off the assertion library from the Jupiter extension, just like JUnit 5 itself did (`maven-it-assertj`, perhaps?).

Granted, AssertJ is more popular than Hamcrest nowadays, but I at least could imagine contributing to a prospective `maven-it-hamcrest`.

**Comment by khmarbaise** [comment]
First thanks for the feedback and if you take a look into the current branch https://github.com/khmarbaise/maven-it-extension/tree/multimodule-build I already separated those parts ...and why not adding a `maven-it-hamcrest` module...yeah sure...

**Comment by khmarbaise** [comment]
Currently I have named the assertj part `maven-it-assertions` but `maven-it-assertj` sounds more appropriate...

**Comment by sewe** [comment]
Yeah, there might even be people wanting `maven-it-truth` further down the road.

At any rate, the multi-module structure looks definitely like the way to go. :+1:

**Comment by khmarbaise** [comment]
Yeah of course truth not to forget about...yeah why not...
