### ISSUE TITLE
Rename @MavenIT into @MavenJupiterExtension

### ISSUE THREAD

**Issue by khmarbaise** [khmarbaise/maven-it-extension#68]
The question is: Do we really need the `@MavenIT` annotation?

* https://junit.org/junit5/docs/current/user-guide/#extensions

Currently the automatic detection of [extensions is turned off by default](https://junit.org/junit5/docs/current/user-guide/#extensions-registration-automatic-enabling)
which means we have to explicit to use the extension which would make the usage at the moment a little less convenient.

**Comment by rfscholte** [comment]
There's another reason why I proposed this. MavenIT is short for MavenIntegrationTest, which is a special kind of MavenTest, so needing both looks weird.
I would consider it renaming it to something like `MavenJupiterRunner` or `MavenJupiterExtension` if that matches the purpose better.

**Comment by khmarbaise** [comment]
The suggestion `MavenJupiterRunner` will likely being mistaken with JUnit 4 which I like to prevent, but `MavenJupiterExtension` looks feasible yeah why not....

**Comment by rfscholte** [comment]
Naming is very hard and also very important. As long as this is a 0.x we should claim the freedom to fix these things.

**Comment by khmarbaise** [comment]
Ah sorry the `why not` was not meant as a question (my fault)...It should be `there is no reason against that renaming`. I will also rename the issue title to fit more the subject.
