### ISSUE TITLE
"Getting started" is hard to find

### ISSUE THREAD

**Issue by rweisleder** [khmarbaise/maven-it-extension#76]
As a first-time user, I tried to get the `itf-jupiter-extension` running. But for me, it was hard to configure my project correctly.

I suggest to
* add a quick "Getting started" to the project's README.md
* move the section "Configuration in Maven" up, maybe behind the "Overview" with the first code example

**Comment by khmarbaise** [comment]
Unfortunately I've heard that from another side as well. So this is a thing which should be improved.  But of course thanks for testing it and giving this feedback which helps a lot.

**Comment by rweisleder** [comment]
I think my second point will be fixed with #78/#79.

**Comment by khmarbaise** [comment]
@rweisleder Could you take a look here: https://github.com/khmarbaise/maven-it-extension/tree/issue-76-getting-started  if the README is more usable now...Thanks.

**Comment by rweisleder** [comment]
Looks good to me!

I don't know if regular users of Maven know where to put the `<testResource>` tag. But if they start to write integration tests maybe they know it has to go inside `<build><testResources>`.

**Comment by khmarbaise** [comment]
I've added the information about `<build>..`...and structure into the read.
