### ISSUE TITLE
Code in section "Configuration in Maven" (user guide) should be copy-pastable

### ISSUE THREAD

**Issue by rweisleder** [khmarbaise/maven-it-extension#77]
The above-mentioned section contains the required dependencies in the format
```xml
<dependency>
  <groupId>com.soebes.itf.jupiter.extension</groupId>
  <artifactId>itf-jupiter-extension</artifactId>
  <version>${project.version}</version>
  <scope>test</scope>
</dependency>
```

But what if a user has a project with `<version>0.1.0</version>`? He would get the oldest available release and Maven wouldn't complain.

Three paragraphs later is a hint
> The given `${project.version}` has to be replaced with the current version of the project which is currently: 0.6.0-SNAPSHOT.

Instead, the snippet should directly contain the latest release version.

And of course, 0.6.0-SNAPSHOT is not available in Maven Central, so this advice is a bit misleading. 😉

**Comment by khmarbaise** [comment]
I'm currently improving the separation with the documentation of the released version and the SNAPSHOT one `master`(See #75) cause the master version is of course not in central only the release part.

**Comment by khmarbaise** [comment]
So the mentioned snippet will currently contain `0.6.0-SNAPSHOT` but will be replaced automatically with the release version with the next release.
