### ISSUE TITLE
Error message "Log4j2 could not find a logging implementation"

### ISSUE THREAD

**Issue by rweisleder** [khmarbaise/maven-it-extension#80]
**Describe the bug**
With the default minimal setup as described in the user guide, the mentioned error is logged on every build.

**To Reproduce**

1. Go to [itf-examples](https://github.com/khmarbaise/maven-it-extension/tree/13f6fba583261b0b5d5e73a27016d7cca446dd2f/itf-examples)
2. Remove `log4j-core` (compile scope) in pom.xml
https://github.com/khmarbaise/maven-it-extension/blob/13f6fba583261b0b5d5e73a27016d7cca446dd2f/itf-examples/pom.xml#L59-L62
3. Run `mvn verify` and look for the mentioned error message right after the beginning of maven-failsafe-plugin

**Expected behavior**
The required dependency on `log4j-core` should be mentioned in the user guide. Or it shouldn't be a required dependency at all.

It may be better if it's a runtime-dependency of `itf-jupiter-extension`. But I don't know if this could cause a logging dependency hell in user projects.

**Comment by khmarbaise** [comment]
This brought me to reconsider the need of the dependency and more important what I'm really logging and if it is really necessary.
