### ISSUE TITLE
Consider different assertThat style

### ISSUE THREAD

**Issue by rfscholte** [khmarbaise/maven-it-extension#82]
In the examples I see `assertThat(result).isSuccessful();`, which looks a bit of bad legacy from maven-verifier.
Instead I'd propose `assertThat(result, isSuccessful());`, so it is in like with the way we are used to work with hamcrest.
This prevents long chains of asserts, makes your code easier to maintain and it opens up a lot of possibilities without the need of adding methods to your `assertThat` implementation.

**Comment by sewe** [comment]
I also prefer Hamcrest's style (`assertThat(result, isSuccessful());`, but `assertThat(result).isSuccessful();` is the way AssertJ works and that cannot be changed.

That being said, as of issue https://github.com/khmarbaise/maven-it-extension/issues/6, the assertions have moved out of the core and into their own artifact (`itf-assertj`), so “all” that remains is creating `itf-hamcrest` with equivalent functionality.

(For what it’s worth, a PR for Hamcrest assertions are on my (long) to-do list, but first I would like to gather some more hands-on experience with using ITF for my personal projects.)
