### ISSUE TITLE
System property maven.home is set but 'java.lang.IllegalStateException: We could not find the maven executable `mvn` somewhere' is thrown

### ISSUE THREAD

**Issue by sparsick** [khmarbaise/maven-it-extension#88]
**Describe the bug**
System property maven.home is set in Intellji but the class `MavenITExtension` is thrown 

```
java.lang.IllegalStateException: We could not find the maven executable `mvn` somewhere
	at com.soebes.itf.jupiter.extension.MavenITExtension.beforeTestExecution(MavenITExtension.java:171)
```

**To Reproduce**

I write following test that fails

```
class MavenLocatorTest {

    @Test
    void findMvn() {
        Properties properties = new Properties();
        properties.setProperty("maven.home", "/home/sparsick/.sdkman/candidates/maven/3.6.3");
        System.setProperties(properties);

        MavenLocator mavenLocatorUnderTest = new MavenLocator();
        Optional<File> mvnLocation = mavenLocatorUnderTest.findMvn();

        assertThat(mvnLocation).isPresent();
    }
}
```

I debugged `MavenLocator`and mvn executable is found but then the method `checkExecutableViaPathEnvironment` is searching mvn in the PATH variable. During the debug session the PATH variable is `/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games` and therefor Optional.empty() is returned. On my CLI `echo $PATH` returns
a different value.
 
**Current behavior**
An exception is thrown

**Expected behavior**
mvn is found and the test start to run indepent if mvn is set in $PATH

**The used versions**
Apache Maven 3.6.3 (cecedd343002696d0abb50b32b541b8a6ba2883f)
Maven home: /home/sparsick/.sdkman/candidates/maven/current
Java version: 11.0.6, vendor: Eclipse OpenJ9, runtime: /home/sparsick/.sdkman/candidates/java/11.0.6.j9-adpt
Default locale: de_DE, platform encoding: UTF-8
OS name: "linux", version: "4.15.0-99-generic", arch: "amd64", family: "unix"

Intellji 2020.1

**Comment by sparsick** [comment]
Unfortunately, the test is not running during the build. I think because I'm setting maven.home to a pseudo path.

**Comment by khmarbaise** [comment]
First thanks for debugging and checking and yes the result is based on the pseudo path. I already had a more or less complete reimplementation for `MavenLocator` incl. tests which has pinged me about that issue. Do you have a chance to check the branch `issue-88-maven-home`  and retest it with your scenario?

**Comment by khmarbaise** [comment]
I have retested that behaviour with itf 0.6.0 and the execution in IDEA does not work as reported with this issue. Retested with the code from the branch it works.

**Comment by khmarbaise** [comment]
Thanks for your report.

**Comment by sparsick** [comment]
I tested your reimplementation of MavenLocator with my scenario and it works like charm.

Thank you for fixing this bug. 

> First thanks for debugging and checking and yes the result is based on the pseudo path. I already had a more or less complete reimplementation for `MavenLocator` incl. tests which has pinged with that issue. Do you have a chance to check the branch `issue-88-maven-home` and retest it with your scenario?
