### ISSUE TITLE
Small FileSystem usage Review

### ISSUE THREAD

**Issue by marschall** [khmarbaise/maven-it-extension#91]
I recently saw your tweet https://twitter.com/khmarbaise/status/1255611454931251207 and your implementation. I wanted to give you a quick feedback. As it doesn't fit into a tweet I opened this issue.

I would say you make good use of the file system API. Nevertheless there are some minor things that could be improved. Most of them are very subjective.

FileSystem related
------------------------

* `com.soebes.itf.jupiter.extension.MavenLocatorTest#create(FileSystem, String, String)` could use `#resolve` instead of `FileSystem#getPath` for the second path, I feel that is more idiomatic.
* `com.soebes.itf.jupiter.extension.MavenLocator#isExecutable(Path)` could use `Files.readAttributes(s, BasicFileAttributes.class)` instead, that way the file gets `stat()` ed only once instead of thrice.

JUnit 5 related
-------------------

* The system property manipulation could be moved into a custom extension
  ```java
  class MavenHomeExtension implements BeforeEachCallback, AfterEachCallback {
  
    private final String mavenHome;
    private Properties backup;
  
    MavenHomeExtension(String mavenHome) {
      this.mavenHome = mavenHome;
    }
  
    @Override
    public void beforeEach(ExtensionContext context) throws Exception {
      backup = new Properties();
      backup.putAll(System.getProperties());
      System.setProperty("maven.home", mavenHome);
    }
  
    @Override
    public void afterEach(ExtensionContext context) {
      System.setProperties(backup);
    }
  }
  ```
  which can then be used like this
  ```java
  @RegisterExtension
  final MavenHomeExtension extension = new MavenHomeExtension(WINDOWS_TOOLS_MAVEN_HOME_DIRECTORY);
  ```
  then we no longer need to copy and paste code in `#beforeEach` and `#restore`
* Something similar could be done for the file system where we could move
  * the creation
  * the initialization of the Maven directory structure
  * the closing

  into the extension. I think that would require different Windows tests for the `.bat` and `.cmd` files. I recognize there is a trade-off there as the code is currently straight forward and easy to follow but has a bit repetition. Changing it to an extension makes it less obvious what is happening.

Stylistic
----------

* `com.soebes.itf.jupiter.extension.MavenLocatorTest#create(FileSystem, String, String)` `mvnBinary` is probably a better variable name than `mvnBatBinary` since it can also be `mvn` and `mvn.cmd`
* `com.soebes.itf.jupiter.extension.MavenLocator#mavenHomeFromSystemProperty()` it feels like there should be an easier, more idiomatic way to do this but I don't see it.
* I'm not aware of any consensus on the best way to use `Optional` in Java. What I feel a more idiomatic approach with less `#isPresent()` could look like is
  ```java
  Optional<Path> findMvn() {
    Optional<Path> executable = mavenHomeFromSystemProperty().map(this::intoPath)
                                                             .map(this::intoBin)
                                                             .flatMap(this::executable);
    if (executable.isPresent()) {
      return executable;
    }
    return checkExecutableViaPathEnvironment();
  }
  ```
  unfortunately I don't see a way to get rid of the last `#isPresent()`.
* `com.soebes.itf.jupiter.extension.MavenLocator#checkExecutableViaPathEnvironment()` regarding the TODO, the path and the file system separator two different things, they are unrelated. Nowhere in the file system code is there any dependency on the path separator.
* `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PreferMavenHome#LINUX_TOOLS_MAVEN_HOME_DIRECTORY` should probably be `static`
* `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PreferMavenHome#LINUX_TOOLS_MAVEN_BIN_DIRECTORYN_HOME_DIRECTORY` should probably be `static`
* `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PathVariable` doesn't seem to change system properties so there should be no need to back them up.

I can create pull requests for the individual issues that you agree with.

**Comment by khmarbaise** [comment]
> I recently saw your tweet https://twitter.com/khmarbaise/status/1255611454931251207 and your implementation. I wanted to give you a quick feedback. As it doesn't fit into a tweet I opened this issue.

That's a great review. Thanks for your time.

> 
> I would say you make good use of the file system API. Nevertheless there are some minor things that could be improved. Most of them are very subjective.

Sure I know that things can be improved.

> 
> ## FileSystem related
> * `com.soebes.itf.jupiter.extension.MavenLocatorTest#create(FileSystem, String, String)` could use `#resolve` instead of `FileSystem#getPath` for the second path, I feel that is more idiomatic.

Done. ✅ 

> * `com.soebes.itf.jupiter.extension.MavenLocator#isExecutable(Path)` could use `Files.readAttributes(s, BasicFileAttributes.class)` instead, that way the file gets `stat()` ed only once instead of thrice.
Hm.. technically I could do that but that would result in a much larger code part
* ```java
    try {
      BasicFileAttributes attr = Files.readAttributes(s, BasicFileAttributes.class);
      FileSystemProvider provider = s.getFileSystem().provider();
      much more code for: isReadable().. and isExecutable()...
   } catch (IOException e) {
     return false;
  }
```
which in the end will save `stat()` calls yes but the readability would be really worse. So I keep the state cause it's easy to understand.

> 
> ## JUnit 5 related
> * The system property manipulation could be moved into a custom extension
>   ```java
>   class MavenHomeExtension implements BeforeEachCallback, AfterEachCallback {
>   
>     private final String mavenHome;
>     private Properties backup;
>   
>     MavenHomeExtension(String mavenHome) {
>       this.mavenHome = mavenHome;
>     }
>   
>     @Override
>     public void beforeEach(ExtensionContext context) throws Exception {
>       backup = new Properties();
>       backup.putAll(System.getProperties());
>       System.setProperty("maven.home", mavenHome);
>     }
>   
>     @Override
>     public void afterEach(ExtensionContext context) {
>       System.setProperties(backup);
>     }
>   }
>   ```
>   
>   
>   which can then be used like this
>   ```java
>   @RegisterExtension
>   final MavenHomeExtension extension = new MavenHomeExtension(WINDOWS_TOOLS_MAVEN_HOME_DIRECTORY);
>   ```
>   
>   
>   then we no longer need to copy and paste code in `#beforeEach` and `#restore`
> * Something similar could be done for the file system where we could move
>   
>   * the creation
>   * the initialization of the Maven directory structure
>   * the closing
>   
>   into the extension. I think that would require different Windows tests for the `.bat` and `.cmd` files. I recognize there is a trade-off there as the code is currently straight forward and easy to follow but has a bit repetition. Changing it to an extension makes it less obvious what is happening.

Yes I know that I could move that to an extension but as you mentioned it's not that obvious what is happening. I already started on a branch to do so. Maybe I will integrate that... not sure at the moment..

> 
> ## Stylistic
> * `com.soebes.itf.jupiter.extension.MavenLocatorTest#create(FileSystem, String, String)` `mvnBinary` is probably a better variable name than `mvnBatBinary` since it can also be `mvn` and `mvn.cmd`

Of course ✅ 

> * `com.soebes.itf.jupiter.extension.MavenLocator#mavenHomeFromSystemProperty()` it feels like there should be an easier, more idiomatic way to do this but I don't see it.
I think I found a simpler solution:
```java
  private Optional<String> mavenHomeFromSystemProperty() {
    return Optional.ofNullable(System.getProperty(MAVEN_HOME));
  }
```

> * I'm not aware of any consensus on the best way to use `Optional` in Java. What I feel a more idiomatic approach with less `#isPresent()` could look like is
>   ```java
>   Optional<Path> findMvn() {
>     Optional<Path> executable = mavenHomeFromSystemProperty().map(this::intoPath)
>                                                              .map(this::intoBin)
>                                                              .flatMap(this::executable);
>     if (executable.isPresent()) {
>       return executable;
>     }
>     return checkExecutableViaPathEnvironment();
>   }
>   ```

Great makes it easier to read.... Done that... ✅ 

>   
>   
>   unfortunately I don't see a way to get rid of the last `#isPresent()`.
> * `com.soebes.itf.jupiter.extension.MavenLocator#checkExecutableViaPathEnvironment()` regarding the TODO, the path and the file system separator two different things, they are unrelated. Nowhere in the file system code is there any dependency on the path separator.

Yes I know but the point is that searching within the `PATH` is OS dependent or FileSystem dependent. 
If you take a look at `File.pathSeparator` which `public static final char pathSeparatorChar = fs.getPathSeparator();` where `private static final FileSystem fs = DefaultFileSystem.getFileSystem();` but unfortunately the `FileSystem` is from `java.io` instead of `java.nio.file` which are different things but very similar. I think the lack is simply that `FileSystem`(java.nio.file) does not defines `getPathSeparator()` that would have made such code more easier...but of course it is not the case at the moment..

> * `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PreferMavenHome#LINUX_TOOLS_MAVEN_HOME_DIRECTORY` should probably be `static`
> * `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PreferMavenHome#LINUX_TOOLS_MAVEN_BIN_DIRECTORYN_HOME_DIRECTORY` should probably be `static`
> * `com.soebes.itf.jupiter.extension.MavenLocatorTest.Linux.PathVariable` doesn't seem to change system properties so there should be no need to back them up.
> 
> I can create pull requests for the individual issues that you agree with.

**Comment by marschall** [comment]
> Hm.. technically I could do that but that would result in a much larger code part
> 
> ```java
>     try {
>       BasicFileAttributes attr = Files.readAttributes(s, BasicFileAttributes.class);
>       FileSystemProvider provider = s.getFileSystem().provider();
>       much more code for: isReadable().. and isExecutable()...
>    } catch (IOException e) {
>      return false;
>   }
> ```

You're correct. I thought the permission methods were on `BasicFileAttributes` but they are on `PosixFileAttributes` and `DosFileAttributes`. Checking for the presence of each and having different code paths makes the code much more verbose. `PosixFileAttributes` is theoretically supported on Windows but this is undocumented and I don't think relying on it is a good idea. Using `#checkAccess` makes the code more verbose.
I don't see how a noticeable performance gain would result from this.


> I think I found a simpler solution:
> 
> ```java
>   private Optional<String> mavenHomeFromSystemProperty() {
>     return Optional.ofNullable(System.getProperty(MAVEN_HOME));
>   }
> ```

Indeed, that reads much better.

**Comment by khmarbaise** [comment]
Many thanks for your review comments.
