### ISSUE TITLE
Add support for editorconfig

### ISSUE THREAD

**Issue by sparsick** [khmarbaise/maven-it-extension#93]
**Is your feature request related to a problem? Please describe.**
[Editorconfig](https://editorconfig.org/) is a trial to specify Editor configuration in a common way.
For example IDEA supports it as default and for other IDE or text editor there exists plugins. 
A beneifit is that you avoid maintaining several code style files for each editor.

**Describe the solution you'd like**
I assume that maven-it-extension use the default Intellj setting, so this setting can be exported to an editorconfig.

**Comment by khmarbaise** [comment]
I have tweaked the `.editorconfig` a little bit and got in line with the `IDEASetup.xml`.
